apiVersion : apps/v1
kind: Deployment
metadata:
  name: instafluffnodejsonazuremulticontainerpods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instafluffnodejsonazuremulticontainerpods
  template:
    metadata:
      labels:
        app: instafluffnodejsonazuremulticontainerpods
    spec:
      containers:
        - name: instafluffnodejsonazuremulticontainerpods
          image: nodejsonakscontainer.azurecr.io/instafluffnodejsonazuremulticontainerpods
          ports:
          - containerPort: 8080
        - name: instafluffnodejsonazuremulticontainerpods-jobs
          image: nodejsonakscontainer.azurecr.io/instafluffnodejsonazuremulticontainerpods-jobs
          ports:
          - containerPort: 8081
